- name: copy the cumulus nvue yaml config file to switch
  ansible.builtin.template:
    src: "{{ config_template }}"
    dest: /tmp/nvue_initial_config.yaml
    mode: 0644

- name: nvue config replace
  ansible.builtin.command: nv config replace /tmp/nvue_initial_config.yaml

- name: nvue config apply
  ansible.builtin.command: nv config apply -y
