- name: "copy the cumulus nvue yaml config file to switch for {{ config_module }} config"
  template:
    src: "{{ config_template }}"
    dest: /tmp/nvue_config.yaml
    mode: 0644

- name: "execute on cumulus: 'nv config patch' for {{ config_module }} config"
  command: nv config patch /tmp/nvue_config.yaml

- name: "execute on cumulus: 'nv config apply' for {{ config_module }} config"
  command: nv config apply -y
