- wait_for_connection:
    timeout: 60
  when: |
    node_provider == 'clab' and ansible_connection == 'network_cli'

- name: "dellos10_config: deploying {{ netsim_action }} from {{ config_template }}, save to startup={{ _save }}"
  vars:
    _save: "{{ 'yes' if netlab_save_config|default(True) else 'no' }}"
  dellemc.os10.os10_config:
    match: "none"
    src: "{{ config_template }}"
    save: "{{ _save }}"
  tags: [ print_action, always ]
  register: os10_output
