- wait_for_connection:
    timeout: 60
  when: |
    netlab_provider == 'clab' and ansible_connection == 'network_cli'

- name: "dellos10_config: deploying {{ netsim_action }} from {{ config_template }}"
  dellemc.os10.os10_config:
    match: "none"
    src: "{{ lookup('template', config_template) }}"
    save: "yes"
  tags: [ print_action, always ]
  register: os10_output
