- wait_for_connection:
    timeout: 60
  when: |
    node_provider == 'clab' and ansible_connection == 'ansible.netcommon.network_cli'

- name: "exos_config: deploying {{ netsim_action }} from {{ config_template }}"
  community.network.exos_config:
    src: "{{ config_template }}"
  tags: [ print_action, always ]
