- template:
    src: "{{ config_template }}"
    dest: /tmp/config-{{ netsim_action }}.sh

- name: "execute config-{{ netsim_action }}.sh to deploy {{ netsim_action }} config from {{ config_template }}"
  command: "/bin/vbash /tmp/config-{{ netsim_action }}.sh"
  become: true
  tags: [ print_action, always ]
