- block:
  - wait_for_connection:
      timeout: 120
      sleep: 3
  - command: /usr/bin/systemctl status vyos.target
    retries: 20
    delay: 3
    register: result
    until: result.rc == 0
  when: |
    netlab_provider == 'clab' and vyos_target_reached is not defined

- set_fact:
    vyos_target_reached: 1

- template:
    src: "{{ config_template }}"
    dest: /tmp/config-{{ netsim_action }}.sh

- name: "execute config-{{ netsim_action }}.sh to deploy {{ netsim_action }} config from {{ config_template }}"
  command: "/bin/vbash /tmp/config-{{ netsim_action }}.sh"
  become: true
  tags: [ print_action, always ]
