- set_fact:
    script_content: "{{ lookup('template',config_template) }}"
    destination_script: "/tmp/config-{{ netsim_action|replace('/', '_') }}.sh"

- template:
    src: vyos-script.j2
    dest: "{{ destination_script }}"

- name: "execute config-{{ netsim_action }}.sh to deploy {{ netsim_action }} config from {{ config_template }}"
  command: "/bin/vbash {{ destination_script }}"
  tags: [ print_action, always ]
  register: cmdout
  failed_when: "'  Set failed' in cmdout.stderr_lines"
