- block:
  - wait_for_connection:
      timeout: 120
      sleep: 3
  - wait_for:
      timeout: 120
      path: /tmp/vyos-config-status
  when: |
    node_provider == 'clab' and vyos_booted is not defined

- set_fact:
    vyos_booted: 1

- set_fact:
    destination_script: "/tmp/config-{{ netsim_action|replace('/', '_') }}.sh"

- template:
    src: "{{ config_template }}"
    dest: "{{ destination_script }}"

- name: "execute config-{{ netsim_action }}.sh to deploy {{ netsim_action }} config from {{ config_template }}"
  command: "/bin/vbash {{ destination_script }}"
  tags: [ print_action, always ]
  register: cmdout
  failed_when: "'  Set failed' in cmdout.stderr_lines"
