#!/usr/bin/env python3
#
# Main netsim-tools CLI command
#

try:
  import netsim
  import netsim.cli
except:
  print("Cannot import netsim Python module, netlab installation is broken")

netsim.cli.lab_commands(__file__)
