#!/usr/bin/env python3
#
# Main netsim-tools CLI command
#
import sys

try:
  import netsim
  import netsim.cli
except Exception as ex:
  print("Cannot import netsim Python module, netlab installation is broken")
  print(ex)
  sys.exit(1)

netsim.cli.lab_commands(__file__)
