# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    # Project-specific exclusions
    "legacy",
    "docs/_build",
    "common.py" # Should be checked if this file is even needed!
]

line-length = 120
indent-width = 2


[lint]
select = [
    "F401", # Module imported but unused
    "F841", # Local variable assigned but never used
    "I",  # import-order (isort)
] 

[lint.per-file-ignores]
# Allow re-exports in __init__.py files
"*/__init__.py" = [
    "F401",  # Module imported but unused
    "F403",  # 'from module import *' used
    "E402",  # Module level import not at top of file
]

# Allow print statements in CLI modules and scripts
"netsim/cli/*.py" = ["T201", "T203"]
"netlab" = ["T201", "T203"]
"*.py" = []

# Test files can be more relaxed
"tests/*.py" = [
    "T201",   # print found
    "T203",   # pprint found
    "S101",   # Use of assert detected
    "PLR2004", # Magic value used in comparison
]

# Scripts and setup files
"setup.py" = ["T201", "T203"]
"**/setup.py" = ["T201", "T203"]


[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
docstring-code-line-length = "dynamic"