#
# Initial configuration of a Linux container is just the networking setup (addressing + routing),
# the /etc/hosts file is created as a clab bind.
#
# The commands to set up Linux networking are executed on the container host in the context
# of container networking namespace so we don't need the 'ip' command or Python in the container.
#
# This task list:
#
# * Creates a random file name that will be used for the initialization script
# * Creates the networking setup script in the temporary file
# * Executes the setup script within the containerlab container namespace
#
---
- set_fact:
    # yamllint disable-line rule:line-length
    exec_script: /tmp/config-{{ lookup('password','/dev/null length=8 chars=ascii_letters') }}-{{ inventory_hostname }}.sh

- name: "Create initial container setup from {{ config_template }}"
  template:
    src: "{{ config_template }}"
    dest: "{{ exec_script }}"
  delegate_to: localhost

- name: "Initial container configuration via {{ exec_script }}"
  shell: |
    set -e
    ip netns exec {{ ansible_host }} bash {{ exec_script }}
  become: true
  delegate_to: localhost
  tags: [ print_action, always ]

- file:
    path: "{{ exec_script }}"
    state: absent
  delegate_to: localhost
