- name: Add VirtualBMC nodes
  command: >
    vbmc add {{ item.name }}
    --port {{ item.ipmi_port }}
    --address {{ item.ipmi_address|default('::') }}
    --username {{ item.ipmi_user|default('admin') }}
    --password {{ item.ipmi_password|default('admin') }}
  tags: [ print_action, always ]
  loop: "{{ vbmc_nodes|default([]) }}"
  when: vbmc.server|default(False)

- name: Start VirtualBMC nodes
  command: "vbmc start {{ item.name }}"
  tags: [ print_action, always ]
  loop: "{{ vbmc_nodes|default([]) }}"
  when: vbmc.server|default(False)