- name: Wait for at least 2 minutes for AOS-CX inside CLAB...
  pause:
    minutes: 2
  when: |
    netlab_provider == 'clab'

- name: Execute local ssh command to check AOS-CX readiness
  local_action:
    module: command
    cmd: "sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ ansible_host }} 'show version'"
  register: command_out
  until: command_out.rc == 0
  retries: 20
  delay: 30
  when: clab.kind is defined
