#
# Wait for NXOS VM in a container to wake up
#
---
- name: Wait for SSH server
  include_tasks: vm-clab-ssh-check.yml
  args:
    apply:
      vars:
        ck_command: show version
        ck_retries: 20
