- name: Ensure FortiGate is ready for configuration
  ansible.builtin.wait_for:
    host: "{{ansible_host}}"
    port: 443
    timeout: 180
    sleep: 10       # time in seconds between checks
    delay: 60       # Initial delay in seconds before first check
    state: started
