- name: Execute local ssh command to check router readiness
  local_action:
    module: command
    cmd: "sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ ansible_host }} '/system/resource/print'"
  register: command_out
  until: command_out.rc == 0
  retries: 10
  delay: 30
  when: clab.kind is defined
