- name: Check that required plugin exists, use 'netlab install grpc' to install it
  vars:
    ansible_connection: nokia.grpc.gnmi
  nokia.grpc.gnmi_config:
    prefix: test-plugin

- name: Wait up to 180s for gNMI(TCP {{sros_grpc_port}}) to be ready on {{ ansible_host }}
  local_action:
    module: wait_for
    port: "{{ sros_grpc_port }}"
    host: "{{ ansible_host }}"
    connect_timeout: 60
    timeout: 180
    sleep: 5
