# Generic routing attributes
#
---
attributes:
  global:
    policy:
      type: dict
      _subtype:
        type: list
        make_list: True
        _subtype: rp_entry

  node:
    policy:

  route_map:
    set: [ locpref, med, weight, prepend ]

no_propagate:
  policy:

_top:                               # Modification of global defaults
  attributes:
    rp_entry:                       # Define routing policy entry
      _description: Routing policy entry
      action:
        type: str
        valid_values: [ permit, deny ]
      sequence:
        type: int
        min_value: 1
        max_value: 32767
      set:
        locpref:
          type: int
          min_value: 0
          max_value: 4294967295
        med:
          type: int
          min_value: 0
          max_value: 32767
        weight:
          type: int
          min_value: 0
          max_value: 32767
        prepend:
          count:
            type: int
            min_value: 1
            max_value: 32
          path: str
        community:
          standard: list
          extended: list
          large: list
          append: bool

features:
  policy: Route map attributes
