# Generic routing attributes
#
---
attributes:
  global:
    policy:
      type: dict
      _keytype: id
      _subtype:
        type: list
        make_list: True
        _subtype: rp_entry
    prefix:
      type: dict
      _keytype: id
      _subtype:
        type: list
        make_list: True
        _subtype: pfx_entry

  node:
    policy:
      merge: global
      _subtype:
        _alt_types: [ NoneType ]
    prefix:
      merge: global
      _subtype:
        _alt_types: [ NoneType ]

  route_map:
    set: [ locpref, med, weight, prepend ]

no_propagate:
  policy:
  prefix:

_top:                               # Modification of global defaults
  attributes:
    rp_entry:                       # Define routing policy entry
      _description: Routing policy entry
      action:
        type: str
        valid_values: [ permit, deny ]
      sequence:
        type: int
        min_value: 1
        max_value: 32767
      set:
        locpref:
          type: int
          min_value: 0
          max_value: 4294967295
        med:
          type: int
          min_value: 0
          max_value: 32767
        weight:
          type: int
          min_value: 0
          max_value: 65535
        prepend:
          count:
            type: int
            min_value: 1
            max_value: 32
          path: str
        community:
          standard: list
          extended: list
          large: list
          append: bool

    pfx_entry:                      # Define prefix list entry
      action:
        type: str
        valid_values: [ permit, deny ]
      sequence:
        type: int
        min_value: 1
        max_value: 32767
      pool:
        type: addr_pool
        _valid_with: [ action, sequence ]
      prefix:
        type: named_pfx
        _valid_with: [ action, sequence ]
      ipv4: { type: ipv4, use: prefix }
      ipv6: { type: ipv6, use: prefix }

features:
  policy:
    set: Route map SET attributes
