- name: Enable SCP
  arista.eos.eos_config:
    lines: aaa authorization exec default local

- name: Copy replacement configuration to Arista EOS device
  include_tasks: _copy_config.yml
  vars:
    netlab_device_disk: ""

- name: Replace running configuration
  eos_command:
    commands: "configure replace flash:replace-config"
