- name: Copy replacement configuration to SR Linux container
  shell: docker cp {{ config_template }} {{ ansible_host }}:/tmp/replace-config
  delegate_to: localhost

- name: Load SR Linux configuration file
  vars:
    ansible_network_os: nokia.srlinux.srlinux
    ansible_connection: ansible.netcommon.httpapi
  nokia.srlinux.cli:
    commands:
    - enter candidate
    - load file /tmp/replace-config
    - commit now save
