#!/bin/bash
#
set -e
set -x
#
# Create bash profile script
#
cat <<SCRIPT >/root/.bash_profile
#!/bin/bash
#
export PS1="\h(bash)# "
echo
echo "Use vtysh to connect to FRR daemon"
echo
SCRIPT
#
# This is an artifact of unknown provenance that should be removed in a year or two (= 2026/2027)
#
# FRR controls these parameters with 'ip forwarding' and 'ipv6 forwarding' commands
#
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=0
#
cat <<SCRIPT >.bash_profile
#!/bin/bash
#
export PS1="\h(bash)$ "
export PATH=$PATH:/usr/sbin
echo 
echo "Use sudo vtysh to connect to FRR daemon"
echo
SCRIPT
#
# Build hosts file
#
#
cat <<SCRIPT >/tmp/hosts
#
# Created by netlab initial
#
10.0.0.1 r1
10.1.0.1 Ethernet1.r1
10.0.0.2 r2
10.1.0.2 Ethernet1.r2
10.1.0.5 Ethernet2.r2
10.0.0.3 r3
10.1.0.6 eth1.r3
SCRIPT
grep "Created by netlab" /etc/hosts || uniq /tmp/hosts >>/etc/hosts
#
# Configure system defaults on Ubuntu
#
hostnamectl set-hostname r3
APT_INSTALL=
#
if which gpg; then
  echo "Package gnupg already installed"
else
  APT_INSTALL="$APT_INSTALL gnupg"
fi
#
if which curl; then
  echo "Package curl already installed"
else
  APT_INSTALL="$APT_INSTALL curl"
fi
#
if which bridge; then
  echo "Package iproute2 already installed"
else
  APT_INSTALL="$APT_INSTALL iproute2"
fi
#
# APT_INSTALL always starts with a blank, so we can't just check if it's empty
# The following hack turns a string that contains only whitespaces into
# an empty string and removes leading whitespaces
#
APT_INSTALL=`echo $APT_INSTALL`
if [ -n "$APT_INSTALL" ]; then
  echo "Installing packages $APT_INSTALL"
  apt-get update -qq && apt-get install -qq $APT_INSTALL
fi
#
# Install FRR on a Ubuntu VM if needed
#
if which /usr/lib/frr/frrinit.sh; then
  echo "FRR already installed, skipping installation"
else
  curl -s https://deb.frrouting.org/frr/keys.asc >/etc/apt/trusted.gpg.d/frr.asc
  FRRVER="frr-stable"
  echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER > /etc/apt/sources.list.d/frr.list
  apt-get update -qq && apt-get install -qq frr frr-pythontools bridge-utils ethtool
fi
#
# Enable FRR modules (if not using containerlab bind-mounted /etc/frr/daemons)
#
#
# Enable FRR daemons
#
echo "isisd=yes" >>/etc/frr/daemons

/usr/lib/frr/frrinit.sh restart

# Set system defaults
#
# Send ARP requests from a sane source IP address
#
sysctl -w net.ipv4.conf.all.arp_announce=2

#
# Create loopbacks, stub and lag/bond devices
#
if [ ! -e /sys/class/net/lo ]; then
  if [ ! -e /sys/devices/virtual/net/lo ]; then
    ip link add lo type dummy
    ip link set dev lo up
  fi
fi

# Disable IPv6 (for IPv4-only interfaces) or SLAAC (if the device is a router)
#
ip link set eth1 down
sysctl -qw net.ipv6.conf.eth1.disable_ipv6=1
ip link set dev eth1 mtu 1500
ip link set eth1 up

#
# Add vtysh.conf file
echo "service integrated-vtysh-config" >/etc/frr/vtysh.conf

#
# Rest of initial configuration done through VTYSH
#
cat >/tmp/config <<CONFIG
hostname r3
!
log file /tmp/logging

!
ip forwarding
frr defaults datacenter
!
interface lo
 no shutdown
 ip address 10.0.0.3/32
!
interface eth1
 no shutdown
 description r3 -> r2
 ip address 10.1.0.6/30
!
do write
CONFIG
vtysh -f /tmp/config
!
exit 0