#!/bin/bash
#
set -e
sysctl -w net.mpls.platform_labels=1048575
#
# Enable MPLS data plane on transit interfaces
#
sysctl -w net.mpls.conf.eth1.input=1
cat >/tmp/config <<CONFIG
!
router isis West
  segment-routing on
  mpls-te router-address 10.0.0.3
  segment-routing prefix 10.0.0.3/32 index 3
do write
CONFIG
vtysh -f /tmp/config
exit 0