inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory/hosts.yaml
    group_file: inventory/groups.yaml
runner:
  plugin: threaded
  options:
    num_workers: 100
logging:
  enabled: false
