# fetch ArubaCX configuration
#
---
- arubanetworks.aoscx.aoscx_command:
    commands:
    - no page
    - show running-config
  register: conf_output

- set_fact:
    ansible_net_config: "{{ conf_output.stdout | default([]) | join('') }}\n"
