#
# Fetch Cumulus NVUE yaml configuration files
#
- name: save cumulus nvue config to file on switch
  shell: nv config show > /tmp/config_save.yaml

- name: fetch cumulus yaml config from switch
  fetch:
    src: "/tmp/config_save.yaml"
    dest: "{{ config_dir }}/{{ inventory_hostname }}/"
    flat: true
