# fetch Fortinet FortiOS configuration using fortios_monitor_fact module
#
---
- name: save fortios config
  fortinet.fortios.fortios_monitor_fact:
    selector: 'system_config_backup'
    vdom: "{{ vdom }}"
    params:
      scope: 'global'
  register: fortios_run_config

- set_fact:
    ansible_net_config: "{{ fortios_run_config.meta.raw }}"
