# fetch Cisco IOS configuration using ios_facts module
#
---
- cisco.ios.ios_facts:
    gather_subset: config

- set_fact:
    ansible_net_config: >-
      {{ "!" + (ansible_net_config|split("!"))[1:]|join("!") }}
