FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

LABEL maintainer="Netlab project <netlab.tools>"
LABEL description="ipmitool - IPMI client for testing"

RUN apt-get update && apt-get install -y \
    ipmitool \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

# Keep container alive so we can run docker exec against it
CMD [ "tail", "-f", "/dev/null" ]
