01-initial:
  _timestamp: '2026-08-09 13:56:52'
  _version: '26.08'
  config: true
  create: true
  up: true
  validate: true
02-config:
  _timestamp: '2026-08-09 13:58:20'
  _version: '26.08'
  config: true
  create: true
  up: true
  validate: true
03-custom:
  _timestamp: '2026-08-09 13:59:38'
  _version: '26.08'
  config: true
  create: true
  up: true
  validate: true
04-reload:
  _timestamp: '2026-08-09 14:00:26'
  _version: '26.08'
  config: true
  create: true
  up: true
  validate: true
05-skip-config:
  _timestamp: '2026-08-09 14:01:26'
  _version: '26.08'
  config: true
  create: true
  up: true
  validate: true
