01-initial:
  _timestamp: '2026-10-02 15:10:15'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
02-config:
  _timestamp: '2026-10-02 15:11:31'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
03-custom:
  _timestamp: '2026-10-02 15:12:51'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
04-reload:
  _timestamp: '2026-10-02 15:13:45'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
05-skip-config:
  _timestamp: '2026-10-02 15:14:44'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
06-netmiko:
  _timestamp: '2026-10-02 15:15:15'
  _version: '26.10'
  config: true
  create: true
  up: true
  validate: true
