---
name: Build netlab devcontainer

on:
  workflow_call:
    inputs:
      docker-tags:
        required: True
        type: string
    secrets:
      GHCR_TOKEN:
        required: True

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.repository == 'ipspace/netlab' && github.actor == 'ipspace'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        imageTag: ${{ inputs.docker-tags }}
        push: always
