---
name: Build netlab devcontainer

on:
  push:
    tags: [ release_* ]

env:
  REGISTRY: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.release_tag.outputs.IMAGE_TAG }}
    steps:
    - name: Find release tag
      id: release_tag
      run: echo "IMAGE_TAG=${GITHUB_REF_NAME#release_}" >> $GITHUB_OUTPUT

  build:
    needs: [ setup ]
    uses: ./.github/workflows/devcontainer-build.yml
    with:
      docker-tags: ${{ needs.setup.outputs.IMAGE_TAG }},latest
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
