---
name: Build netlab devcontainer

on:
  push:
    tags: [ release_* ]

env:
  REGISTRY: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Find release tag
      run: echo "IMAGE_TAG=${GITHUB_REF_NAME#release_}" >> $GITHUB_ENV

  build:
    uses: ./.github/workflows/devcontainer-build.yml
    with:
      docker-tags: ${{ env.IMAGE_TAG }},latest
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
