---
name: Build netlab devcontainer

on:
  push:
    tags: [ release_* ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.repository == 'ipspace/netlab'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Find release tag
      run: echo "IMAGE_TAG=${GITHUB_REF_NAME#release_}" >> $GITHUB_ENV
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        imageTag: ${{ env.IMAGE_TAG }},latest
        push: always
