---
name: Build netlab devcontainer with :devc tag whenever a push is made in the 'devc' branch

on:
  push:
    branches: [ devc ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    uses: ./.github/workflows/devcontainer-build.yml
    with:
      docker-tags: devc
      pip-options: --pre
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
