name: Check integration tests with "none" device

on:
  pull_request:
    paths:
    - '**.py'
    - '**.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [ "3.8", "3.12", "3.13" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Inspect GH event context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "========== GITHUB CONTEXT ============"
        echo "$GITHUB_CONTEXT"
    - name: Run Mypy
      if: ${{ github.event.pull_request.head.repo.full_name != 'ipspace/netlab' }}
      run: |
        set -e
        mypy -p netsim
        for file in netsim/extra/*/plugin.py; do
          python3 -m mypy $file
        done
    - name: Run transformation tests
      if: ${{ github.event.pull_request.head.repo.full_name != 'ipspace/netlab' }}
      run: |
        cd tests
        PYTHONPATH="../" pytest
    - name: Check integration tests
      run: |
        cd tests
        ./check-integration-tests.sh
