name: Check YAML file syntax
on:
  push:
    branches-ignore: [ devc ]
    paths:
    - '**.yml'

  pull_request:
    paths:
    - '**.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install yamllint
      run: |
        python -m pip install yamllint
    - name: Lint YAML files
      run: |
        set -e
        shopt -s extglob
        shopt -s globstar
        yamllint --no-warnings netsim/*.yml netsim/**/*.yml tests/**/*.yml
